// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnukaxltltqldnywsbzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudWtheGx0bHRxbGRueXdzYnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTQ2NTcsImV4cCI6MjA4ODU5MDY1N30.wTHjP6kZp7BqtIbNeWJRaRCAlhsEnsP46Goi2jc02wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});